### ISSUE TITLE
Faulty install pack

### ISSUE THREAD

**Issue by ghost** [nasa/NTL-Asteroid-Data-Hunter#11]
Hi, this "App" looks promising but is not useable right now.

The MAC/OS download installs a group of folders and files that don't/can't run as per your installation guide. As part of the software development lifecycle its always good to test your install against the actual instructions you require people to follow on a variety of devices.

Creating a folder "NASA's Asteroid Data Hunter" is the first problem, there is a special character (Apostrophe) in the Folder or Path name. When I renamed the folder to "NASAs Asteroid Data Hunter" you could then start the program as per the instructions. 

(It still doesn't work though - see other open ticket on "Hunting failure due to other backend issue")

**Comment by mrmillares** [comment]
Hi, do you have any suggestion to solve this?

MacBookProMrMillares:~ mrmillares$ /Applications/NASAs\ Asteroid\ Data\ Hunter/start.sh 

Automatic deployment tool - Start
TCSASSEMBLER

Unable to find any JVMs matching version "(null)".
No Java runtime present, try --request to install.
JAVA_HOME=
warurl=/Applications/NASAs Asteroid Data Hunter/asteroid/hunter.war
applicationpath=/Applications/NASAs Asteroid Data Hunter
/Applications/NASA

Thanks in advance.

**Comment by rashid-sial** [comment]
@astroswanny, thanks for the feedback. No one else has reported that error - and I've been able to install and launch the app using the detailed instructions in the user guide. I'll respond to your other ticket regarding the hunting failure.

@mrmillares, please try this:
1. Delete the Asteroid Data Hunter folder from your Applications directory
2. Install the latest version of Java: java.com
3. Re-install the app.

Please let me know how it goes.

**Comment by ghost** [comment]
Rashid,

Thanks, the Mac OS installer works now.

The Windows install for MAC VM still has a "unable to write" permissions error which if you change the directory away from the Programs directory it then it installs ok but still doesn't work.
HTTP ERROR 500

Problem accessing /dashboard. Reason:

```
Server Error
```

Caused by:

org.apache.jasper.JasperException: PWC6033: Error in Javac compilation for JSP

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:5: package javax.servlet.jsp does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:8: package org.apache.jasper.runtime does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:9: package org.apache.jasper.runtime does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:11: cannot find symbol
symbol  : class JspFactory
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:21: package org.apache.jasper.runtime does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:22: package org.apache.jasper.runtime does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:24: package org.glassfish.jsp.api does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:344: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:362: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:380: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:398: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:416: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:434: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:452: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:470: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:488: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:506: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:524: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:542: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:560: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:578: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:596: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:614: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:632: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:663: package javax.servlet.jsp.tagext does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:663: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:681: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:712: package javax.servlet.jsp.tagext does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:712: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:730: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:761: package javax.servlet.jsp.tagext does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:761: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:779: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:810: package javax.servlet.jsp.tagext does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:810: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:828: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:11: cannot find symbol
symbol  : variable JspFactory
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:31: cannot find symbol
symbol  : method getServletConfig()
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:31: package org.apache.jasper.runtime does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:32: cannot find symbol
symbol  : method getServletConfig()
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:32: package org.apache.jasper.runtime does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:43: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:47: cannot find symbol
symbol  : class JspWriter
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:48: incompatible types
found   : org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp
required: java.lang.Object

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:49: cannot find symbol
symbol  : class JspWriter
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:50: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:62: package org.glassfish.jsp.api does not exist

PWC6197: An error occurred at line: 75 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:188: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6197: An error occurred at line: 75 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:188: package org.apache.jasper.runtime does not exist

PWC6197: An error occurred at line: 77 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:192: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6197: An error occurred at line: 77 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:192: package org.apache.jasper.runtime does not exist

PWC6197: An error occurred at line: 79 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:196: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6197: An error occurred at line: 79 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:196: package org.apache.jasper.runtime does not exist

PWC6197: An error occurred at line: 81 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:200: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6197: An error occurred at line: 81 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:200: package org.apache.jasper.runtime does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:332: cannot find symbol
symbol  : class SkipPageException
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:346: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:347: cannot find symbol
symbol  : class JspWriter
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6197: An error occurred at line: 23 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:349: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6197: An error occurred at line: 23 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:349: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6197: An error occurred at line: 23 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:349: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:354: package javax.servlet.jsp.tagext does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:364: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:365: cannot find symbol
symbol  : class JspWriter
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6197: An error occurred at line: 27 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:367: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6197: An error occurred at line: 27 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:367: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6197: An error occurred at line: 27 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:367: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:372: package javax.servlet.jsp.tagext does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:382: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:383: cannot find symbol
symbol  : class JspWriter
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6197: An error occurred at line: 29 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:385: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6197: An error occurred at line: 29 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:385: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6197: An error occurred at line: 29 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:385: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:390: package javax.servlet.jsp.tagext does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:400: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:401: cannot find symbol
symbol  : class JspWriter
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6197: An error occurred at line: 32 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:403: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6197: An error occurred at line: 32 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:403: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6197: An error occurred at line: 32 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:403: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:408: package javax.servlet.jsp.tagext does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:418: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:419: cannot find symbol
symbol  : class JspWriter
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6197: An error occurred at line: 33 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:421: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6197: An error occurred at line: 33 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:421: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6197: An error occurred at line: 33 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:421: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:426: package javax.servlet.jsp.tagext does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:436: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:437: cannot find symbol
symbol  : class JspWriter
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6197: An error occurred at line: 34 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:439: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6197: An error occurred at line: 34 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:439: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6197: An error occurred at line: 34 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:439: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:444: package javax.servlet.jsp.tagext does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:454: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:455: cannot find symbol
symbol  : class JspWriter
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6197: An error occurred at line: 37 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:457: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6197: An error occurred at line: 37 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:457: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6197: An error occurred at line: 37 in the jsp file: /WEB-INF/views/header.jsp
PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:457: package org.apache.taglibs.standard.tag.rt.core does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:462: package javax.servlet.jsp.tagext does not exist

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:472: cannot find symbol
symbol  : class PageContext
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

PWC6199: Generated servlet error:
string:///viewDashboard_jsp.java:473: cannot find symbol
symbol  : class JspWriter
location: class org.apache.jsp.WEB_002dINF.views.viewDashboard_jsp

```
at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:129)
at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:299)
at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:392)
at org.apache.jasper.compiler.Compiler.compile(Compiler.java:453)
at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:625)
at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:374)
at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:492)
at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:378)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:276)
at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:103)
at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:238)
at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:264)
at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1208)
at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:992)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:939)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:844)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
at org.eclipse.jetty.server.Server.handle(Server.java:370)
at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
at java.lang.Thread.run(Thread.java:662)
```

Also can you please clarify the Webpage says Requirements MacOS 10.2.x the Documentation says MacOS 10.10.x you might want to tidy that up as well.

**Comment by rashid-sial** [comment]
For Windows, uninstall the app, install the latest version of Java, and then re-install the app to your desktop (or another folder you can write to). Please let me know if it still doesn't work. Please also remember to keep the command prompt window open anytime you're using the app.

Regarding the download web page, the versioning issue has been fixed - thanks!

**Comment by ghost** [comment]
Rashid,

Thanks for your patience. Observing some of the behaviour, I think your install notes should say:

"Before installation, Open your default browser and download the latest version of Java.

Chomeinstal8u40 for Chrome
JavaSetUp8u40 for Firefox"

That will ensure that when your script pops the browser, its going to pop the default browser, and you may need the appropriate browser plugins etc.

ALSO I have installed this on a native Windows machine running Windows 7 Home Premium service pack 1 it fails even more spectacularly.

The CMD windows pops and closes without launching. When you open the CMD manually and drag the SH file in you find the real reason..... it will not run the program on an x32 Bit machine, you have an x64 Bit compile in your installer.

Are your able to create an 32 bit version?

So I suggest you update your Compatability matrix with that information as well.

Clearly I have to go and buy a new PC to run the program ;-)

Thanks again for your patience.

Regards
Peter

**Comment by rashid-sial** [comment]
Peter, thanks for your patience and so sorry about the issues you experienced. The feedback you provided is golden - and we'll def. make sure to incorporate it in the next release.

**Comment by ghost** [comment]
Rashid,

Thanks, I completely understand the need to have a 64 bit system to
maximize the speed of data processing etc.
Given the "proposed market" for the tool - amateurs and schools etc, by
limiting the App to only MAC OS 10.10.x Yosemite and 64 Bit Windows it kind
of "downselects" the number people who could use the tool with out serious
upgrades to their PCs.

However poor performance due to overdriving your compute power also leads
to frustration - Its always a difficult balancing act.

Thanks again.
Regards
Peter

**Comment by hptuttle** [comment]
I have to second Peter's comment with great disappointment. I attempted to install on a Windows 7 32-bit system.  First I found that the link to download the Windows installer provides a tar file, not a zip file!  OK, untarrred it with Cygwin.  But then the .bat installer fails without a visible message, till I manually run the bat in a command prompt window: "The version of java.exe is not compatible with the version of Windows you're running. ..."

So I suggest that to save further folks from disappointment, you revise the "Prerequisites" to include the fact that one must have 64-bit Windows 7, not 32-bit.  

Rich Schmidt
Burleith Observatory (I13)
