### ISSUE TITLE
File RAW to File FIT

### ISSUE THREAD

**Issue by rapalarapala** [nasa/NTL-Asteroid-Data-Hunter#15]
Hello,

I need your help.

I have many photos of night sky taken with my telescope in RAW format, the application Asteroid Data Hunter need 4 photos in FIT format.

You can inform the FIT format specifications to convert my RAW files to FIT.

Thank you,

Leandro

**Comment by pauledd** [comment]
Hi there
I am in the same situation. My RAW images are of type "cr2" (Canon). I can convert them to fits files with rawtran (http://integral.physics.muni.cz/rawtran/). But loading them to ADH I get the error:
"Hunting Failed due to the backend issue."
console shows:
...
at java.lang.Thread.run(Thread.java:662)
Caused by: 
java.lang.NullPointerException
    at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1234)
    at java.text.DateFormat.parse(DateFormat.java:335)
    at gov.nasa.asteroid.tester.AsteroidDetectorTester.doExec(AsteroidDetectorTester.java:1578)
...
I used the "unfiltered" option in rawtran but thats maybe wrong

**Comment by rapalarapala** [comment]
Hello,

The problem nobody answer.
